// <auto-generated>
// Code generated by luis:generate:cs
// Tool github: https://github.com/microsoft/botframework-cli
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class DeploymentChatbot: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Check_Deployment,
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Lists
            public string[][] EnvironmentEntity;
            public string[][] LanguageEntity;
            public string[][] ServiceEntity;
            public string[][] TeamNameEntity;


            // Composites
            public class _InstanceOctopus_Deployment_Entity
            {
                public InstanceData[] Build;
                public InstanceData[] Environment;
                public InstanceData[] Service;
                public InstanceData[] TeamName;
                public InstanceData[] Language;
            }
            public class Octopus_Deployment_EntityClass
            {
                // NOTE: Each entity string must be a 2-D Array - the Microsoft Bot Framework only generates them as 1-D arrays
                // when this CS file is generated via the luis:generate:cs command. Be sure to add the extra array 
                // in order for the program to process the LUIS result correctly.
                public string[][] Build;
                public string[][] Environment;
                public string[][] Service;
                public string[][] TeamName;
                public string[][] Language;
                [JsonProperty("$instance")]
                public _InstanceOctopus_Deployment_Entity _instance;
            }
            public Octopus_Deployment_EntityClass[] Octopus_Deployment_Entity;

            // Instance
            public class _Instance
            {
                public InstanceData[] Build;
                public InstanceData[] Environment;
                public InstanceData[] EnvironmentEntity;
                public InstanceData[] Language;
                public InstanceData[] LanguageEntity;
                public InstanceData[] Octopus_Deployment_Entity;
                public InstanceData[] Service;
                public InstanceData[] ServiceEntity;
                public InstanceData[] TeamName;
                public InstanceData[] TeamNameEntity;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<DeploymentChatbot>(
                JsonConvert.SerializeObject(
                    result,
                    new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Error = OnError }
                )
            );
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        private static void OnError(object sender, ErrorEventArgs args)
        {
            // If needed, put your custom error logic here
            Console.WriteLine(args.ErrorContext.Error.Message);
            args.ErrorContext.Handled = true;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
